title: Man Blong Kuk
author: cgriff02
email: 
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Blog ya i tokbaot hao nao man i save kuk mo semtaem bae i gat sam resipi bakegen. Traem folo blo luk ol gudfala kakae
  seedless

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
